//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Threading.Tasks;
using schemas.sfa.gov.uk.cpds.gatewayservice;

[assembly: ContractNamespace("http://schemas.sfa.gov.uk/cpds.gatewayservice", ClrNamespace = "schemas.sfa.gov.uk.cpds.gatewayservice")]

namespace schemas.sfa.gov.uk.cpds.gatewayservice
{
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.Serialization;

    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [CollectionDataContract(Name = "UKPRNCollection", Namespace = "http://schemas.sfa.gov.uk/cpds.gatewayservice", ItemName = "UKPRN")]
    public class UKPRNCollection : List<UKPRN>
    {
    }

    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "UKPRN", Namespace = "http://schemas.sfa.gov.uk/cpds.gatewayservice")]
    public partial class UKPRN : object, IExtensibleDataObject
    {

        private ExtensionDataObject extensionDataField;

        private string UKPRNDataField;

        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [DataMember()]
        public string UKPRNData
        {
            get
            {
                return this.UKPRNDataField;
            }
            set
            {
                this.UKPRNDataField = value;
            }
        }
    }

    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [CollectionDataContract(Name = "UPINCollection", Namespace = "http://schemas.sfa.gov.uk/cpds.gatewayservice", ItemName = "UPIN")]
    public class UPINCollection : List<UPIN>
    {
    }

    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "UPIN", Namespace = "http://schemas.sfa.gov.uk/cpds.gatewayservice")]
    public partial class UPIN : object, IExtensibleDataObject
    {

        private ExtensionDataObject extensionDataField;

        private string UpinDataField;

        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [DataMember()]
        public string UpinData
        {
            get
            {
                return this.UpinDataField;
            }
            set
            {
                this.UpinDataField = value;
            }
        }
    }
}


[GeneratedCode("System.ServiceModel", "4.0.0.0")]
[ServiceContract(Namespace = "http://schemas.sfa.gov.uk/cpds.gatewayservice", ConfigurationName = "GatewayServiceContract")]
public interface GatewayServiceContract
{

    [OperationContract(Action = "GetProvidersByUKPRN", ReplyAction = "http://schemas.sfa.gov.uk/cpds.gatewayservice/GatewayServiceContract/GetProviders" +
        "ByUKPRNResponse")]
    GProvByUKPRNResponse GetProvidersByUKPRN(GProvByUKPRINRequest request);

    [OperationContract(Action = "GetProvidersByUKPRN", ReplyAction = "http://schemas.sfa.gov.uk/cpds.gatewayservice/GatewayServiceContract/GetProviders" +
        "ByUKPRNResponse")]
    Task<GProvByUKPRNResponse> GetProvidersByUKPRNAsync(GProvByUKPRINRequest request);

    [OperationContract(Action = "GetProviderSummaryByName", ReplyAction = "http://schemas.sfa.gov.uk/cpds.gatewayservice/GatewayServiceContract/GetProviderS" +
        "ummaryByNameResponse")]
    GProvByNameResponse GetProviderSummaryByName(GProvByNameRequest request);

    [OperationContract(Action = "GetProviderSummaryByName", ReplyAction = "http://schemas.sfa.gov.uk/cpds.gatewayservice/GatewayServiceContract/GetProviderS" +
        "ummaryByNameResponse")]
    Task<GProvByNameResponse> GetProviderSummaryByNameAsync(GProvByNameRequest request);

    [OperationContract(Action = "GetProvidersByUpin", ReplyAction = "http://schemas.sfa.gov.uk/cpds.gatewayservice/GatewayServiceContract/GetProviders" +
        "ByUpinResponse")]
    GProvByUPINResponse GetProvidersByUpin(GProvByUPINRequest request);

    [OperationContract(Action = "GetProvidersByUpin", ReplyAction = "http://schemas.sfa.gov.uk/cpds.gatewayservice/GatewayServiceContract/GetProviders" +
        "ByUpinResponse")]
    Task<GProvByUPINResponse> GetProvidersByUpinAsync(GProvByUPINRequest request);
}

[DebuggerStepThrough()]
[GeneratedCode("System.ServiceModel", "4.0.0.0")]
[MessageContract(IsWrapped = false)]
public partial class GProvByUKPRINRequest
{

    [MessageBodyMember(Namespace = "http://schemas.sfa.gov.uk/cpds.gatewayservice", Order = 0)]
    public UKPRNCollection UKPRNs;

    public GProvByUKPRINRequest()
    {
    }

    public GProvByUKPRINRequest(UKPRNCollection UKPRNs)
    {
        this.UKPRNs = UKPRNs;
    }
}

[DebuggerStepThrough()]
[GeneratedCode("System.ServiceModel", "4.0.0.0")]
[MessageContract(IsWrapped = false)]
public partial class GProvByUKPRNResponse
{

    [MessageBodyMember(Namespace = "http://schemas.sfa.gov.uk/cpds.gatewayservice", Order = 0)]
    public string RawCPDSResponse;

    public GProvByUKPRNResponse()
    {
    }

    public GProvByUKPRNResponse(string RawCPDSResponse)
    {
        this.RawCPDSResponse = RawCPDSResponse;
    }
}

[DebuggerStepThrough()]
[GeneratedCode("System.ServiceModel", "4.0.0.0")]
[MessageContract(IsWrapped = false)]
public partial class GProvByNameRequest
{

    [MessageBodyMember(Namespace = "http://schemas.sfa.gov.uk/cpds.gatewayservice", Order = 0)]
    public string TradingName;

    public GProvByNameRequest()
    {
    }

    public GProvByNameRequest(string TradingName)
    {
        this.TradingName = TradingName;
    }
}

[DebuggerStepThrough()]
[GeneratedCode("System.ServiceModel", "4.0.0.0")]
[MessageContract(IsWrapped = false)]
public partial class GProvByNameResponse
{

    [MessageBodyMember(Namespace = "http://schemas.sfa.gov.uk/cpds.gatewayservice", Order = 0)]
    public string RawCPDSResponse;

    public GProvByNameResponse()
    {
    }

    public GProvByNameResponse(string RawCPDSResponse)
    {
        this.RawCPDSResponse = RawCPDSResponse;
    }
}

[DebuggerStepThrough()]
[GeneratedCode("System.ServiceModel", "4.0.0.0")]
[MessageContract(IsWrapped = false)]
public partial class GProvByUPINRequest
{

    [MessageBodyMember(Namespace = "http://schemas.sfa.gov.uk/cpds.gatewayservice", Order = 0)]
    public UPINCollection UPINs;

    public GProvByUPINRequest()
    {
    }

    public GProvByUPINRequest(UPINCollection UPINs)
    {
        this.UPINs = UPINs;
    }
}

[DebuggerStepThrough()]
[GeneratedCode("System.ServiceModel", "4.0.0.0")]
[MessageContract(IsWrapped = false)]
public partial class GProvByUPINResponse
{

    [MessageBodyMember(Namespace = "http://schemas.sfa.gov.uk/cpds.gatewayservice", Order = 0)]
    public string RawCPDSResponse;

    public GProvByUPINResponse()
    {
    }

    public GProvByUPINResponse(string RawCPDSResponse)
    {
        this.RawCPDSResponse = RawCPDSResponse;
    }
}

[GeneratedCode("System.ServiceModel", "4.0.0.0")]
public interface GatewayServiceContractChannel : GatewayServiceContract, IClientChannel
{
}

[DebuggerStepThrough()]
[GeneratedCode("System.ServiceModel", "4.0.0.0")]
public partial class GatewayServiceContractClient : ClientBase<GatewayServiceContract>, GatewayServiceContract
{

    public GatewayServiceContractClient()
    {
    }

    public GatewayServiceContractClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public GatewayServiceContractClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public GatewayServiceContractClient(string endpointConfigurationName, EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public GatewayServiceContractClient(Binding binding, EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public GProvByUKPRNResponse GetProvidersByUKPRN(GProvByUKPRINRequest request)
    {
        return base.Channel.GetProvidersByUKPRN(request);
    }

    public Task<GProvByUKPRNResponse> GetProvidersByUKPRNAsync(GProvByUKPRINRequest request)
    {
        return base.Channel.GetProvidersByUKPRNAsync(request);
    }

    public GProvByNameResponse GetProviderSummaryByName(GProvByNameRequest request)
    {
        return base.Channel.GetProviderSummaryByName(request);
    }

    public Task<GProvByNameResponse> GetProviderSummaryByNameAsync(GProvByNameRequest request)
    {
        return base.Channel.GetProviderSummaryByNameAsync(request);
    }

    public GProvByUPINResponse GetProvidersByUpin(GProvByUPINRequest request)
    {
        return base.Channel.GetProvidersByUpin(request);
    }

    public Task<GProvByUPINResponse> GetProvidersByUpinAsync(GProvByUPINRequest request)
    {
        return base.Channel.GetProvidersByUpinAsync(request);
    }
}
